# Generated by Django 4.0.6 on 2022-07-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pariente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('relacion', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
